services:
  whatsapp-bot:
    build: .
    container_name: whatsapp_registration_bot
    restart: unless-stopped
    # Configuration des volumes pour conserver les données en dehors du conteneur
    volumes:
      - ./inscriptions_photos:/app/inscriptions_photos
      - ./inscriptions_pdf:/app/inscriptions_pdf
      - ./utilisateurs.json:/app/utilisateurs.json
      # Ce dossier garde en mémoire la session WhatsApp (évite de rescanner le QR code à chaque reboot)
      - ./.wwebjs_auth:/app/.wwebjs_auth
    environment:
      - NODE_ENV=production